import { test, expect, addresses, demoPassword, shift, login } from './fixtures'

test.use({ seedStays: true })
test('ADMIN: usuarios, revocación inmediata, último ADMIN, dashboard y auditoría', async ({ page, browser, data }) => {
  await login(page, addresses.admin)
  await page.goto('/admin/users/new')
  await page.getByLabel('Nombre', { exact: true }).fill('Usuario gestionado E2E')
  await page.getByLabel('Correo', { exact: true }).fill('managed@example.test')
  await page.getByLabel('Contraseña', { exact: true }).fill(demoPassword)
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill(demoPassword)
  await page.getByRole('button', { name: 'Crear usuario', exact: true }).click()
  await page.getByRole('link', { name: 'Consultar usuario creado', exact: true }).click()
  const path = new URL(page.url()).pathname
  const context = await browser.newContext({ baseURL: 'http://localhost:3002' })
  try {
    const managed = await context.newPage(); await login(managed, 'managed@example.test')
    await page.getByLabel('Nuevo rol').selectOption('EMPLEADO')
    await page.getByRole('button', { name: 'Cambiar rol', exact: true }).click()
    await page.getByRole('button', { name: 'Confirmar cambio', exact: true }).click()
    await expect(page.getByText('managed@example.test · EMPLEADO · Activo', { exact: true })).toBeVisible()
    await managed.reload(); await expect(managed).toHaveURL(/\/login$/)
    for (const label of ['Desactivar usuario', 'Activar usuario']) {
      await page.getByRole('button', { name: label, exact: true }).click()
      await page.getByRole('button', { name: 'Confirmar cambio', exact: true }).click()
      await expect(page.getByRole('button', { name: label === 'Desactivar usuario' ? 'Activar usuario' : 'Desactivar usuario', exact: true })).toBeVisible()
    }
  } finally { await context.close() }
  await page.goto('/admin/users')
  await page.getByLabel('Nombre o correo').fill('managed@example.test')
  await page.getByRole('button', { name: 'Buscar usuarios' }).click()
  await page.getByRole('link', { name: 'Consultar Usuario gestionado E2E' }).click()
  await expect(page).toHaveURL(new RegExp(path + '$'))
  await page.goto('/admin/users/' + data.admin.id)
  await page.getByRole('button', { name: 'Desactivar usuario', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar cambio', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('ADMIN')
  await page.goto('/admin/dashboard')
  // Include both sides of midnight so a run crossing the hotel's day boundary stays deterministic.
  await page.getByLabel('Desde', { exact: true }).fill(shift(data.today, -1))
  await page.getByLabel('Hasta (excluido)', { exact: true }).fill(shift(data.today, 3))
  await page.getByRole('button', { name: 'Consultar métricas' }).click()
  const metric = (title: string) => page.getByRole('article').filter({ has: page.getByRole('heading', { name: title, exact: true }) })
  await expect(metric('Reservas creadas').locator('p').first()).toHaveText('5')
  await expect(metric('Llegadas programadas').locator('p').first()).toHaveText('2')
  await expect(metric('Salidas programadas').locator('p').first()).toHaveText('2')
  await expect(metric('Ocupación reservada')).toContainText('4 / 24 noches de habitación')
  await expect(metric('Ingreso simulado neto').locator('p').first()).toContainText('680.00')
  await page.goto('/admin/audit-events')
  await page.getByLabel('Acción', { exact: true }).fill('USER_ROLE_CHANGED')
  await page.getByRole('button', { name: 'Filtrar auditoría' }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.getByRole('button', { name: /^Ver evento / }).click()
  const detail = page.getByRole('region', { name: 'Detalle seguro de auditoría' })
  await expect(detail).toContainText('oldRole')
  await expect(detail).toContainText('EMPLEADO')
  await expect(detail).not.toContainText(demoPassword)
})
